variables:
  JEKYLL_ENV: production

stages:
  - publish

pages:
  image: ruby:3.1-bookworm
  stage: publish
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - public
  script:
    - apt-get update -qq -o Acquire::Retries=3
    - apt-get install --fix-missing -qq -o Acquire::Retries=3 libvips libimage-exiftool-perl perl-doc
    - exiftool "-gps*=" -overwrite_original src/photos/original
    - gem install bundler
    - bundle install
    - bundle exec jekyll build --baseurl "$CI_PAGES_URL" -d public

